CategoryTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: CategoryTable
    KeySchema:
      - AttributeName: client_id
        KeyType: HASH
      - AttributeName: name
        KeyType: RANGE 
    AttributeDefinitions:
      - AttributeName: name
        AttributeType: 'S'
      - AttributeName: client_id
        AttributeType: 'S'      
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1